repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
        exclude: demo-doordash/charts/fluent-bit/dashboards/fluent-bit.json
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: |
          (?x)^(
            test/testdata/buffer_test_payload_injection.json|
            test/testdata/buffer_test_payload_full.json
          )
      - id: trailing-whitespace
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-cyclo
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      # - id: go-critic
      #  # args: [-disable=sloppyTypeAssert]
      #  args: ["-v", "-enable='yodaStyleExpr'", "-disable=sloppyTypeAssert"]
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
      - id: go-mod-vendor

  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
      - id: go-lint
      # - id: go-unit-tests
      - id: gofumpt
      - id: go-err-check
      - id: go-static-check
      # - id: golangci-lint
      # - id: go-ruleguard # requires https://github.com/quasilyte/go-ruleguard
      #    args: [rules/rules.go] # required
