name: Check code quality

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
          cache-dependency-path: |
            go.sum
            examples/**/go.sum
      - name: Install pre-commit
        run: |
          python -m pip install -U pip
          python -m pip install pre-commit
      - name: Install pre-commit hooks
        run: |
          pre-commit install
      - name: Install Go tools
        run: |
          ./scripts/install-dev-tools.sh
      - name: Run pre-commit
        run: |
          pre-commit run -a
      - name: Code coverage Lib
        run: |
          go test ./... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out
      - name: Build Examples
        run: |
          ( cd examples/client; go build )
          ( cd examples/readme; go build )
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
