name: TruffleHog Secrets Scan
on: [push, pull_request]

permissions:
  actions: write  # Needed for skip-duplicate-jobs job
  contents: read

jobs:
  # Special job which automatically cancels old runs for the same branch, prevents runs for the
  # same file set which has already passed, etc.
  pre_job:
    name: Skip Duplicate Jobs Pre Job
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@12aca0a884f6137d619d6a8a09fcc3406ced5281 # v5.3.0
        with:
          cancel_others: 'true'
          github_token: ${{ github.token }}

  TruffleHog:
    runs-on: ubuntu-latest
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' || github.ref_name == 'main' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: scan-pr
        uses: trufflesecurity/trufflehog@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: HEAD
          extra_args: --debug --only-verified --max-depth=${{ github.event.pull_request.commits }}
            --exclude-paths=${{ inputs.exclude-paths }}
      - name: scan-push
        uses: trufflesecurity/trufflehog@main
        if: ${{ github.event_name == 'push' }}
        with:
          path: ./
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --debug --only-verified --exclude-paths=${{ inputs.exclude-paths }}
